from pydantic import BaseModel, Field
from typing import List, Optional

class ExtractedSignal(BaseModel):
    detector: str
    signal_name: str
    confidence: float
    details: dict = Field(default_factory=dict)

class DetectorResult(BaseModel):
    is_ai: bool
    confidence: float
    signals: List[ExtractedSignal] = Field(default_factory=list)
    explanation: Optional[str] = None

class AnalysisResponse(BaseModel):
    ai_generated_probability: float = Field(..., description="Probability (0 to 1) that the image is AI-generated")
    confidence_score: float = Field(..., description="System's confidence in its own prediction (0 to 1)")
    c2pa_verified: bool = Field(False, description="Whether cryptographic provenance is valid")
    watermark_detected: bool = Field(False, description="Did we find invisible watermarks (e.g. from SynthID or SD)")
    metadata_ai_hint: bool = Field(False, description="Flags like 'Software: Midjourney' in EXIF")
    forensic_signals: List[str] = Field(default_factory=list, description="Unique identifiers of forensic signals extracted")
    explanation: str = Field(..., description="Human-readable forensic explanation")
    
    class Config:
        json_schema_extra = {
            "example": {
                "ai_generated_probability": 0.87,
                "confidence_score": 0.91,
                "c2pa_verified": False,
                "watermark_detected": True,
                "metadata_ai_hint": True,
                "forensic_signals": [
                    "diffusion_noise_pattern",
                    "frequency_artifacts"
                ],
                "explanation": "Image likely generated by diffusion model."
            }
        }
